version: '3.9'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    networks:
      - rimdesk
networks:
  rimdesk: