apiVersion: skaffold/v3
kind: Config
metadata:
  name: product-api
build:
  artifacts:
    - image: rimdesk/product-api
      docker:
        dockerfile: dockerfile
manifests:
  kustomize:
    paths:
      - manifest/base
profiles:
  - name: prod
    build:
      artifacts:
        - image: 004237575886.dkr.ecr.us-east-1.amazonaws.com/rimdesk/product-api
          docker:
            dockerfile: dockerfile
    manifests:
      kustomize:
        paths:
          - manifest/overlays/prod
