apiVersion: v1
kind: ConfigMap
metadata:
  name: product-api
data:
  APP.NAME: "RIMDesk Product API"
  APP.PORT: "8080"
  APP.ENV: "development"
  KC.BASE_URL: "https://accounts.rimdesk.com"
  KC.REALM: "rimdesk"
  KC.CLIENT_ID: "citadel"
  DB.HOST: ""
  DB.TYPE: "sqlite"
  DB.PORT: ""
  DB.USER: ""
  DB.PASS: ""
  DB.NAME: "rimdesk_products_db"