apiVersion: v1
kind: ConfigMap
metadata:
  name: product-api
data:
  APP.NAME: "RIMDesk Product API"
  APP.PORT: "8080"
  APP.ENV: "development"
  KC.BASE_URL: "https://accounts.rimdesk.com"
  KC.REALM: "rimdesk"
  KC.CLIENT_ID: "citadel"
  DB.HOST: "rimdesk.cenz8zww3kgg.us-east-1.rds.amazonaws.com"
  DB.TYPE: "postgres"
  DB.PORT: "5432"
  DB.USER: "rimdesk"
  DB.PASS: "uHdCTAAcgYasmptU.8ric"
  DB.NAME: "rimdesk_products_db"